name: play_install_referrer
description: >
  A Flutter plugin for the Android Play Install Referrer API.
  You can use it to securely retrieve referral content from Google Play.
version: 0.6.0
homepage: https://github.com/tvbstw/play_install_referrer
repository: https://github.com/tvbstw/play_install_referrer

environment:
  sdk: ^3.12.0
  flutter: ">=3.44.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.chunkytofustudios.play_install_referrer
        pluginClass: PlayInstallReferrerPlugin
